# frozen_string_literal: true

# User A
test_user_a = User.create(username: 'testa', password: 'testa')

# Store Types A
grocery_a = StoreType.create(name: 'Grocery_a', user: test_user_a)
pet_a = StoreType.create(name: 'Pet_a', user: test_user_a)
fast_food_a = StoreType.create(name: 'Fast Food_a', user: test_user_a)
general_a = StoreType.create(name: 'General_a', user: test_user_a)

# Stores A
hyvee_a = Store.create(name: 'Hyvee_a', store_type: grocery_a, user: test_user_a)
aldi_a = Store.create(name: 'ALDI_a', store_type: grocery_a, user: test_user_a)
price_chopper_a = Store.create(name: 'Price Chopper_a', store_type: grocery_a, user: test_user_a)
petsmart_a = Store.create(name: 'Petsmart_a', store_type: pet_a, user: test_user_a)
target_a = Store.create(name: 'Target_a', store_type: general_a, user: test_user_a)
dollar_tree_a = Store.create(name: 'Dollar Tree_a', store_type: general_a, user: test_user_a)
tacobell_a = Store.create(name: 'Taco Bell_a', store_type: fast_food_a, user: test_user_a)
imos_a = Store.create(name: "Imo's_a", store_type: fast_food_a, user: test_user_a)

# Purchases with items A
purch = Purchase.create(purchase_date: Date.current, total: 61.11, store: hyvee_a, user: test_user_a)
Item.create(name: 'Hamburger Buns', price: 2.19, purchase: purch, user: test_user_a)
Item.create(name: 'Bread', price: 1.99, purchase: purch, user: test_user_a)
Item.create(name: 'Water Flavoring', price: 2.99, purchase: purch, user: test_user_a)
Item.create(name: 'Roma Tomatoes', price: 1.42, purchase: purch, user: test_user_a)
Item.create(name: 'Pizza', price: 2.99, purchase: purch, user: test_user_a)
Item.create(name: 'Pizza', price: 2.99, purchase: purch, user: test_user_a)
Item.create(name: 'Pizza', price: 2.99, purchase: purch, user: test_user_a)
Item.create(name: 'Cheddar Cheese', price: 2.68, purchase: purch, user: test_user_a)
Item.create(name: 'Russet Potatoes', price: 2.74, purchase: purch, user: test_user_a)
Item.create(name: 'Tortillas', price: 3.99, purchase: purch, user: test_user_a)
Item.create(name: 'Bagels', price: 2.19, purchase: purch, user: test_user_a)
Item.create(name: 'Mini Pizza Dough', price: 2.97, purchase: purch, user: test_user_a)
Item.create(name: 'Buttermilk Biscuits', price: 3.29, purchase: purch, user: test_user_a)
Item.create(name: 'Flaky Biscuits', price: 3.29, purchase: purch, user: test_user_a)
Item.create(name: 'Sour Cream', price: 1.99, purchase: purch, user: test_user_a)
Item.create(name: 'Daybreak', price: 13.89, purchase: purch, user: test_user_a)
Item.create(name: '24pk Water', price: 3.49, purchase: purch, user: test_user_a)

purch = Purchase.create(purchase_date: 1.day.ago, total: 111.83, store: target_a, user: test_user_a)
Item.create(name: 'Shirts', price: 30.00, purchase: purch, user: test_user_a)
Item.create(name: 'Pop-Tarts', price: 3.99, purchase: purch, user: test_user_a)
Item.create(name: 'MarketPantry', price: 2.99, purchase: purch, user: test_user_a)
Item.create(name: 'Chobani', price: 2.69, purchase: purch, user: test_user_a)
Item.create(name: 'MRKT PNTRY', price: 3.99, purchase: purch, user: test_user_a)
Item.create(name: 'Poppi', price: 2.29, purchase: purch, user: test_user_a)
Item.create(name: 'Monster', price: 2.69, purchase: purch, user: test_user_a)
Item.create(name: 'Monste', price: 2.69, purchase: purch, user: test_user_a)
Item.create(name: 'GG Milk', price: 1.99, purchase: purch, user: test_user_a)
Item.create(name: 'GG Sauce', price: 1.69, purchase: purch, user: test_user_a)
Item.create(name: 'REALEMON', price: 2.39, purchase: purch, user: test_user_a)
Item.create(name: 'STONYFIELD Yogurt', price: 7.49, purchase: purch, user: test_user_a)
Item.create(name: 'Dove', price: 5.99, purchase: purch, user: test_user_a)
Item.create(name: 'HeroCsmetics', price: 6.99, purchase: purch, user: test_user_a)
Item.create(name: 'Olive & June', price: 7.49, purchase: purch, user: test_user_a)
Item.create(name: 'Cotton Comfort', price: 17.99, purchase: purch, user: test_user_a)

# Item.create(name: '', price: , purchase: purch)
# Worse examples past this point, need to be redone
purch = Purchase.create(purchase_date: 1.week.ago, total: 29.21, store: aldi_a, user: test_user_a)
Item.create(name: 'Burgers', price: 5.99, purchase: purch, user: test_user_a)
Item.create(name: 'Burger Buns', price: 2.99, purchase: purch, user: test_user_a)
Item.create(name: 'Frozen Fish', price: 2.99, purchase: purch, user: test_user_a)
Item.create(name: 'Frozen Chicken', price: 6.99, purchase: purch, user: test_user_a)
Item.create(name: 'Pizza', price: 7.60, purchase: purch, user: test_user_a)

purch = Purchase.create(purchase_date: 2.weeks.ago, total: 12.05, store: hyvee_a, user: test_user_a)
Item.create(name: 'Hotdogs', price: 3.99, purchase: purch, user: test_user_a)
Item.create(name: 'Buns', price: 1.99, purchase: purch, user: test_user_a)
Item.create(name: 'Soda', price: 1.99, purchase: purch, user: test_user_a)
Item.create(name: 'Yogurt', price: 2.99, purchase: purch, user: test_user_a)

purch = Purchase.create(purchase_date: 3.weeks.ago, total: 15.35, store: price_chopper_a, user: test_user_a)
Item.create(name: 'Orange Juice', price: 3.99, purchase: purch, user: test_user_a)
Item.create(name: 'Bread', price: 1.99, purchase: purch, user: test_user_a)
Item.create(name: 'Cheese Slices', price: 3.99, purchase: purch, user: test_user_a)
Item.create(name: 'Ramen', price: 3.99, purchase: purch, user: test_user_a)

purch = Purchase.create(purchase_date: 2.weeks.ago, total: 23.54, store: tacobell_a, user: test_user_a)
Item.create(name: 'tacos', price: 15.22, purchase: purch, user: test_user_a)
Item.create(name: 'tacos', price: 2.99, purchase: purch, user: test_user_a)

purch = Purchase.create(purchase_date: 1.weeks.ago, total: 42.84, store: petsmart_a, user: test_user_a)
Item.create(name: 'Dog Food', price: 39.22, purchase: purch, user: test_user_a)

purch = Purchase.create(purchase_date: 5.weeks.ago, total: 42.84, store: petsmart_a, user: test_user_a)
Item.create(name: 'Dog Food', price: 39.22, purchase: purch, user: test_user_a)

purch = Purchase.create(purchase_date: Date.current, total: 23.54, store: imos_a, user: test_user_a)
Item.create(name: 'pizza', price: 21.23, purchase: purch, user: test_user_a)

purch = Purchase.create(purchase_date: 5.weeks.ago, total: 33.54, store: tacobell_a, user: test_user_a)
Item.create(name: 'tacos', price: 25.22, purchase: purch, user: test_user_a)
Item.create(name: 'tacos', price: 2.99, purchase: purch, user: test_user_a)

# User B
test_user_b = User.create(username: 'testb', password: 'testb')

# Store Types B
grocery_b = StoreType.create(name: 'Grocery_b', user: test_user_b)
pet_b = StoreType.create(name: 'Pet_b', user: test_user_b)
fast_food_b = StoreType.create(name: 'Fast Food_b', user: test_user_b)
general_b = StoreType.create(name: 'General_b', user: test_user_b)

# Stores B
hyvee_b = Store.create(name: 'Hyvee_b', store_type: grocery_b, user: test_user_b)
aldi_b = Store.create(name: 'ALDI_b', store_type: grocery_b, user: test_user_b)
price_chopper_b = Store.create(name: 'Price Chopper_b', store_type: grocery_b, user: test_user_b)
petsmart_b = Store.create(name: 'Petsmart_b', store_type: pet_b, user: test_user_b)
target_b = Store.create(name: 'Target_b', store_type: general_b, user: test_user_b)
dollar_tree_b = Store.create(name: 'Dollar Tree_b', store_type: general_b, user: test_user_b)
tacobell_b = Store.create(name: 'Taco Bell_b', store_type: fast_food_b, user: test_user_b)
imos_b = Store.create(name: "Imo's_b", store_type: fast_food_b, user: test_user_b)

# Purchases with items B
purch = Purchase.create(purchase_date: Date.current, total: 61.11, store: hyvee_b, user: test_user_b)
Item.create(name: 'Hamburger Buns', price: 2.19, purchase: purch, user: test_user_b)
Item.create(name: 'Bread', price: 1.99, purchase: purch, user: test_user_b)
Item.create(name: 'Water Flavoring', price: 2.99, purchase: purch, user: test_user_b)
Item.create(name: 'Roma Tomatoes', price: 1.42, purchase: purch, user: test_user_b)
Item.create(name: 'Pizza', price: 2.99, purchase: purch, user: test_user_b)
Item.create(name: 'Pizza', price: 2.99, purchase: purch, user: test_user_b)
Item.create(name: 'Pizza', price: 2.99, purchase: purch, user: test_user_b)
Item.create(name: 'Cheddar Cheese', price: 2.68, purchase: purch, user: test_user_b)
Item.create(name: 'Russet Potatoes', price: 2.74, purchase: purch, user: test_user_b)
Item.create(name: 'Tortillas', price: 3.99, purchase: purch, user: test_user_b)
Item.create(name: 'Bagels', price: 2.19, purchase: purch, user: test_user_b)
Item.create(name: 'Mini Pizza Dough', price: 2.97, purchase: purch, user: test_user_b)
Item.create(name: 'Buttermilk Biscuits', price: 3.29, purchase: purch, user: test_user_b)
Item.create(name: 'Flaky Biscuits', price: 3.29, purchase: purch, user: test_user_b)
Item.create(name: 'Sour Cream', price: 1.99, purchase: purch, user: test_user_b)
Item.create(name: 'Daybreak', price: 13.89, purchase: purch, user: test_user_b)
Item.create(name: '24pk Water', price: 3.49, purchase: purch, user: test_user_b)

purch = Purchase.create(purchase_date: 1.day.ago, total: 111.83, store: target_b, user: test_user_b)
Item.create(name: 'Shirts', price: 30.00, purchase: purch, user: test_user_b)
Item.create(name: 'Pop-Tarts', price: 3.99, purchase: purch, user: test_user_b)
Item.create(name: 'MarketPantry', price: 2.99, purchase: purch, user: test_user_b)
Item.create(name: 'Chobani', price: 2.69, purchase: purch, user: test_user_b)
Item.create(name: 'MRKT PNTRY', price: 3.99, purchase: purch, user: test_user_b)
Item.create(name: 'Poppi', price: 2.29, purchase: purch, user: test_user_b)
Item.create(name: 'Monster', price: 2.69, purchase: purch, user: test_user_b)
Item.create(name: 'Monste', price: 2.69, purchase: purch, user: test_user_b)
Item.create(name: 'GG Milk', price: 1.99, purchase: purch, user: test_user_b)
Item.create(name: 'GG Sauce', price: 1.69, purchase: purch, user: test_user_b)
Item.create(name: 'REALEMON', price: 2.39, purchase: purch, user: test_user_b)
Item.create(name: 'STONYFIELD Yogurt', price: 7.49, purchase: purch, user: test_user_b)
Item.create(name: 'Dove', price: 5.99, purchase: purch, user: test_user_b)
Item.create(name: 'HeroCsmetics', price: 6.99, purchase: purch, user: test_user_b)
Item.create(name: 'Olive & June', price: 7.49, purchase: purch, user: test_user_b)
Item.create(name: 'Cotton Comfort', price: 17.99, purchase: purch, user: test_user_b)

# Item.create(name: '', price: , purchase: purch)
# Worse examples past this point, need to be redone
purch = Purchase.create(purchase_date: 1.week.ago, total: 29.21, store: aldi_b, user: test_user_b)
Item.create(name: 'Burgers', price: 5.99, purchase: purch, user: test_user_b)
Item.create(name: 'Burger Buns', price: 2.99, purchase: purch, user: test_user_b)
Item.create(name: 'Frozen Fish', price: 2.99, purchase: purch, user: test_user_b)
Item.create(name: 'Frozen Chicken', price: 6.99, purchase: purch, user: test_user_b)
Item.create(name: 'Pizza', price: 7.60, purchase: purch, user: test_user_b)

purch = Purchase.create(purchase_date: 2.weeks.ago, total: 12.05, store: hyvee_b, user: test_user_b)
Item.create(name: 'Hotdogs', price: 3.99, purchase: purch, user: test_user_b)
Item.create(name: 'Buns', price: 1.99, purchase: purch, user: test_user_b)
Item.create(name: 'Soda', price: 1.99, purchase: purch, user: test_user_b)
Item.create(name: 'Yogurt', price: 2.99, purchase: purch, user: test_user_b)

purch = Purchase.create(purchase_date: 3.weeks.ago, total: 15.35, store: price_chopper_b, user: test_user_b)
Item.create(name: 'Orange Juice', price: 3.99, purchase: purch, user: test_user_b)
Item.create(name: 'Bread', price: 1.99, purchase: purch, user: test_user_b)
Item.create(name: 'Cheese Slices', price: 3.99, purchase: purch, user: test_user_b)
Item.create(name: 'Ramen', price: 3.99, purchase: purch, user: test_user_b)

purch = Purchase.create(purchase_date: 2.weeks.ago, total: 23.54, store: tacobell_b, user: test_user_b)
Item.create(name: 'tacos', price: 15.22, purchase: purch, user: test_user_b)
Item.create(name: 'tacos', price: 2.99, purchase: purch, user: test_user_b)

purch = Purchase.create(purchase_date: 1.weeks.ago, total: 42.84, store: petsmart_b, user: test_user_b)
Item.create(name: 'Dog Food', price: 39.22, purchase: purch, user: test_user_b)

purch = Purchase.create(purchase_date: 5.weeks.ago, total: 42.84, store: petsmart_b, user: test_user_b)
Item.create(name: 'Dog Food', price: 39.22, purchase: purch, user: test_user_b)

purch = Purchase.create(purchase_date: Date.current, total: 23.54, store: imos_b, user: test_user_b)
Item.create(name: 'pizza', price: 21.23, purchase: purch, user: test_user_b)

purch = Purchase.create(purchase_date: 5.weeks.ago, total: 33.54, store: tacobell_b, user: test_user_b)
Item.create(name: 'tacos', price: 25.22, purchase: purch, user: test_user_b)
Item.create(name: 'tacos', price: 2.99, purchase: purch, user: test_user_b)